title: Botshare
description: A learning platform website
remote_theme: just-the-docs/just-the-docs

#plugins:
 # - jekyll-default-layout

url: https://Merilynn-64.github.io/botsharebook
search_enable : true
color_scheme: light
primary_color: dark
