title: Botshare
description: A documentation platform for botshare
remote_theme: just-the-docs/just-the-docs

repository: openAMRobot/Botshare_book
aux_links:
  "View on GitHub": https://github.com/openAMRobot
aux_links_new_tab: true

search_enabled: true
search.tokenizer_separator: /[\s/]+/

nav_sort: case-insensitive

collections:
  docs:
    output: true
    permalink: /:path/
    sidebar:
      nav: "docs"

just_the_docs:
  collections:
    docs:
      name: Documentation
      nav_exclude: false

footer_content: "Copyright © 2025 Botshare AI. All rights reserved."
last_edit_timestamp: true
last_edit_time_format: "%b %e %Y"

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter_opts:
    block:
      line_numbers: false

url: https://Merilynn-64.github.io/botsharebook
search_enable : true
color_scheme: light
primary_color: dark
nav:
  - home: index.md
  - course: 
    - overview: overview.md
    - training program: training_program.md
