title: The book Test
description: A learning platform website
theme: just-the-docs
plugins:
  - jekyll-default-layout
url: https://YOUR-USERNAME.github.io/YOUR-SITE-NAME

  Template Repository: https://github.com/Merilynn-64/botsharebooktitle: My Book Test
